FROM alpine

RUN apk add --no-cache git

ARG BUILD_PHASE 
ENV BUILD_PHASE={BUILD_PHASE}

ARG REPO_ACCESS_TOKEN
ENV REPO_ACCESS_TOKEN={REPO_ACCESS_TOKEN}

ARG REPO_URL
ENV REPO_URL={REPO_URL}

ARG KUSTOMIZE_PATH
ENV KUSTOMIZE_PATH={KUSTOMIZE_PATH}

ARG GITHUB_USER
ENV GITHUB_USER={GITHUB_USER}

ARG GITHUB_USER_EMAIL
ENV GITHUB_USER_EMAIL={GITHUB_USER_EMAIL}

ARG IMAGE
ENV IMAGE={IMAGE}

ARG IMAGE_TAG
ENV IMAGE_TAG={IMAGE_TAG}

WORKDIR /app

COPY entrypoint.sh /app/

CMD ["/bin/sh", "/app/entrypoint.sh"]
